from __future__ import annotations

from dataclasses import dataclass
from math import exp
import numpy as np

from .config import HumanConfig


@dataclass
class PBPKIntervention:
    oral_probe_mg: float = 0.0


class ReferencePBPKModel:
    """Mass-conserving reduced PBPK model for a generic reference compound.

    The compound is intentionally not mapped to a marketed medicine. Distribution
    is perfusion-limited with configurable tissue:plasma partition coefficients.
    Hepatic clearance uses a well-stirred liver: intrinsic elimination is taken
    from the explicit liver compartment, while the reported systemic clearance
    is the corresponding flow-limited value. Renal clearance is filtration-only
    and therefore scales with fraction unbound and current GFR.

    This is a PBPK *architecture demonstration*, not a validated drug model.
    """

    _TISSUES = (
        ("liver", "probe_liver_mg", "pbpk_liver_volume_l", "pbpk_liver_flow_l_min", "pbpk_kp_liver"),
        ("kidney", "probe_kidney_mg", "pbpk_kidney_volume_l", "pbpk_kidney_flow_l_min", "pbpk_kp_kidney"),
        ("muscle", "probe_muscle_mg", "pbpk_muscle_volume_l", "pbpk_muscle_flow_l_min", "pbpk_kp_muscle"),
        ("adipose", "probe_adipose_mg", "pbpk_adipose_volume_l", "pbpk_adipose_flow_l_min", "pbpk_kp_adipose"),
        ("rest", "probe_rest_mg", "pbpk_rest_volume_l", "pbpk_rest_flow_l_min", "pbpk_kp_rest"),
    )

    def __init__(self, config: HumanConfig):
        self.cfg = config

    def apply_instant_intervention(self, state, intervention: PBPKIntervention):
        dose = max(0.0, float(intervention.oral_probe_mg))
        state.probe_gut_mg += dose
        state.probe_administered_mg += dose
        self._refresh_derived(state)
        return state

    def step(self, state, exercise: float, dt: float):
        remaining = float(dt)
        while remaining > 1e-12:
            ds = min(self.cfg.pbpk_internal_step_min, remaining)
            self._substep(state, float(np.clip(exercise, 0.0, 1.0)), ds)
            remaining -= ds
        self._refresh_derived(state)
        return state

    def _organ_flows(self, state, exercise: float) -> dict[str, float]:
        c = self.cfg
        # Relative perfusion weights are redistributed by exercise, then normalized
        # to the cardiac output generated by the closed-loop circulation.
        weights = {
            "liver": c.pbpk_liver_flow_l_min * (1.0 - 0.25 * exercise),
            "kidney": c.pbpk_kidney_flow_l_min * (1.0 - 0.35 * exercise),
            "muscle": c.pbpk_muscle_flow_l_min * (1.0 + 4.0 * exercise),
            "adipose": c.pbpk_adipose_flow_l_min * (1.0 - 0.20 * exercise),
            "rest": c.pbpk_rest_flow_l_min * (1.0 + 0.20 * exercise),
        }
        total_weight = max(1e-9, sum(weights.values()))
        cardiac_output = max(0.2, float(getattr(state, "cardiac_output_l_min", 5.0)))
        flows = {k: cardiac_output * v / total_weight for k, v in weights.items()}
        state.probe_total_tissue_flow_l_min = float(sum(flows.values()))
        return flows

    def _substep(self, state, exercise: float, ds: float):
        c = self.cfg
        plasma_volume = max(0.5, float(state.plasma_volume_l))
        flows = self._organ_flows(state, exercise)

        # Hepatic well-stirred clearance and first-pass extraction.
        qh = max(1e-9, flows["liver"])
        fu_clint = c.pbpk_fraction_unbound * c.pbpk_hepatic_clint_l_min
        hepatic_cl = qh * fu_clint / (qh + fu_clint)
        hepatic_extraction = float(np.clip(hepatic_cl / qh, 0.0, 0.95))

        # First-order GI absorption with first-pass extraction.
        absorbed = state.probe_gut_mg * (1.0 - exp(-c.pbpk_absorption_ka_per_min * ds))
        absorbed = min(state.probe_gut_mg, max(0.0, absorbed))
        state.probe_gut_mg -= absorbed
        first_pass_loss = absorbed * hepatic_extraction
        systemic_absorbed = absorbed - first_pass_loss
        state.probe_plasma_mg += systemic_absorbed
        state.probe_eliminated_hepatic_mg += first_pass_loss

        # Perfusion-limited tissue exchange. Calculate all transfers from the same
        # pre-exchange plasma state, then scale positive tissue uptake if needed.
        c_plasma = state.probe_plasma_mg / plasma_volume
        transfers: dict[str, float] = {}
        positive_total = 0.0
        for name, amount_attr, volume_attr, flow_attr, kp_attr in self._TISSUES:
            amount = max(0.0, float(getattr(state, amount_attr)))
            volume = max(1e-9, float(getattr(c, volume_attr)))
            kp = max(1e-6, float(getattr(c, kp_attr)))
            q = max(0.0, float(flows[name]))
            c_tissue = amount / volume
            rate_mg_min = q * (c_plasma - c_tissue / kp)
            transfer = rate_mg_min * ds
            if transfer >= 0.0:
                positive_total += transfer
            else:
                transfer = -min(-transfer, amount)
            transfers[name] = transfer

        if positive_total > state.probe_plasma_mg and positive_total > 0.0:
            scale = state.probe_plasma_mg / positive_total
            for name in transfers:
                if transfers[name] > 0.0:
                    transfers[name] *= scale

        net_to_tissues = 0.0
        for name, amount_attr, *_ in self._TISSUES:
            transfer = transfers[name]
            setattr(state, amount_attr, max(0.0, getattr(state, amount_attr) + transfer))
            net_to_tissues += transfer
        state.probe_plasma_mg = max(0.0, state.probe_plasma_mg - net_to_tissues)

        # Systemic hepatic elimination belongs to the explicit liver compartment.
        # For a perfusion-limited liver, C_liver/Kp is the venous-equivalent
        # concentration and fu*CLint acts on that concentration. At steady state
        # this produces Q*fu*CLint/(Q+fu*CLint), i.e. ``hepatic_cl`` above, without
        # withdrawing the same clearance directly from the central compartment.
        liver_volume = max(1e-9, float(c.pbpk_liver_volume_l))
        liver_kp = max(1e-6, float(c.pbpk_kp_liver))
        liver_venous_equivalent = (
            max(0.0, float(state.probe_liver_mg)) / liver_volume / liver_kp
        )
        hepatic_loss = min(
            max(0.0, float(state.probe_liver_mg)),
            max(0.0, fu_clint * liver_venous_equivalent * ds),
        )

        # Filtration removes unbound probe from plasma.
        c_plasma = state.probe_plasma_mg / plasma_volume
        gfr_l_min = max(0.0, state.gfr_ml_min) / 1000.0
        renal_cl = (
            c.pbpk_fraction_unbound
            * gfr_l_min
            * c.pbpk_renal_filtration_multiplier
        )
        renal_loss = min(
            max(0.0, float(state.probe_plasma_mg)),
            max(0.0, renal_cl * c_plasma * ds),
        )

        state.probe_liver_mg -= hepatic_loss
        state.probe_plasma_mg -= renal_loss
        state.probe_eliminated_hepatic_mg += hepatic_loss
        state.probe_eliminated_renal_mg += renal_loss

        # Effect-site concentration is a virtual biophase state, not part of mass.
        c_plasma = state.probe_plasma_mg / plasma_volume
        alpha = 1.0 - exp(-ds / max(1e-6, c.pbpk_effect_site_tau_min))
        state.probe_effect_site_mg_l += (
            c_plasma - state.probe_effect_site_mg_l
        ) * alpha

        state.probe_hepatic_clearance_l_min = hepatic_cl
        state.probe_renal_clearance_l_min = renal_cl
        self._refresh_derived(state)

    @staticmethod
    def _refresh_derived(state):
        plasma_volume = max(0.5, float(state.plasma_volume_l))
        state.probe_plasma_mg_l = state.probe_plasma_mg / plasma_volume

        current_body = (
            state.probe_gut_mg
            + state.probe_plasma_mg
            + state.probe_liver_mg
            + state.probe_kidney_mg
            + state.probe_muscle_mg
            + state.probe_adipose_mg
            + state.probe_rest_mg
        )
        eliminated = state.probe_eliminated_hepatic_mg + state.probe_eliminated_renal_mg
        state.probe_total_body_mg = current_body
        state.probe_mass_balance_error_mg = (
            state.probe_administered_mg - eliminated - current_body
        )

    def refresh_concentrations_with_config(self, state):
        c = self.cfg
        self._refresh_derived(state)
        state.probe_liver_mg_l = state.probe_liver_mg / c.pbpk_liver_volume_l
        state.probe_kidney_mg_l = state.probe_kidney_mg / c.pbpk_kidney_volume_l
        return state
