"""Explicit units and semantics registry for the public RL interface.

This is not a symbolic dimensional-analysis engine. It is a machine-checkable
registry preventing undocumented variables/actuators from entering the policy
interface without declared physical meaning.
"""

OBSERVATION_UNITS = {
    "time_to_go_fraction": "dimensionless fraction of episode horizon",
    "sensor_glucose_mg_dl": "mg/dL",
    "cgm_measurement_age_min": "min",
    "monitor_measurement_age_min": "min",
    "blood_gas_measurement_age_min": "min",
    "chemistry_measurement_age_min": "min",
    "hemodynamic_measurement_age_min": "min",
    "glucose_mg_dl": "mg/dL",
    "insulin_uU_ml": "uU/mL",
    "gut_carbs_g": "g glucose-equivalent",
    "lactate_mmol_l": "mmol/L",
    "dalla_ra_mg_kg_min": "mg/kg/min",
    "dalla_egp_mg_kg_min": "mg/kg/min",
    "dalla_u_mg_kg_min": "mg/kg/min",
    "heart_rate_bpm": "1/min",
    "map_mmHg": "mmHg",
    "systolic_pressure_mmHg": "mmHg",
    "diastolic_pressure_mmHg": "mmHg",
    "cardiac_output_l_min": "L/min",
    "stroke_volume_ml": "mL",
    "central_venous_pressure_mmHg": "mmHg",
    "pulmonary_artery_pressure_mmHg": "mmHg",
    "cv_ejection_fraction": "dimensionless",
    "plasma_volume_l": "L",
    "hematocrit_fraction": "dimensionless",
    "hemoglobin_g_dl": "g/dL",
    "respiratory_rate_bpm": "1/min",
    "tidal_volume_l": "L/breath",
    "pao2_mmHg": "mmHg",
    "paco2_mmHg": "mmHg",
    "bicarbonate_mmol_l": "mmol/L",
    "ph_arterial": "dimensionless",
    "spo2_pct": "%",
    "alveolar_ventilation_l_min": "L/min",
    "pulmonary_shunt_fraction": "dimensionless",
    "pulmonary_vq_log_sd": "dimensionless model dispersion",
    "pulmonary_diffusing_capacity_relative": "relative",
    "pulmonary_mean_vq_ratio": "dimensionless",
    "pulmonary_low_vq_perfusion_fraction": "dimensionless",
    "pulmonary_high_vq_ventilation_fraction": "dimensionless",
    "pulmonary_capillary_transit_time_s": "s",
    "pulmonary_diffusion_equilibration_fraction": "dimensionless",
    "pulmonary_aa_gradient_mmHg": "mmHg",
    "pulmonary_alveolar_dead_space_fraction": "dimensionless",
    "pulmonary_enghoff_dead_space_fraction": "dimensionless",
    "pulmonary_recruitment_fraction": "dimensionless",
    "pulmonary_hpv_resistance_multiplier": "dimensionless resistance ratio",
    "pulmonary_perfusion_redistribution_index": "dimensionless total-variation fraction",
    "pulmonary_mean_distending_pressure_cmH2O": "cmH2O",
    "pulmonary_effective_capillary_blood_volume_ml": "mL",
    "pulmonary_hypoxic_perfusion_fraction": "dimensionless",
    "pulmonary_transpulmonary_pressure_end_exp_cmH2O": "cmH2O",
    "pulmonary_transpulmonary_pressure_end_insp_cmH2O": "cmH2O",
    "pulmonary_passive_equivalent_plateau_pressure_cmH2O": "cmH2O",
    "pulmonary_airway_driving_pressure_cmH2O": "cmH2O",
    "pulmonary_lung_compliance_l_cmH2O": "L/cmH2O",
    "pulmonary_chest_wall_compliance_l_cmH2O": "L/cmH2O",
    "pulmonary_respiratory_system_compliance_l_cmH2O": "L/cmH2O",
    "pulmonary_lung_strain": "dimensionless",
    "pulmonary_overdistension_fraction": "dimensionless",
    "pulmonary_intrathoracic_pressure_delta_cmH2O": "cmH2O",
    "pulmonary_mechanical_pvr_multiplier": "dimensionless resistance ratio",
    "pulmonary_mechanical_power_j_min": "J/min",
    "respiratory_airway_resistance_cmH2O_s_l": "cmH2O*s/L",
    "respiratory_cycle_auto_peep_cmH2O": "cmH2O",
    "respiratory_cycle_dynamic_hyperinflation_l": "L",
    "respiratory_cycle_peak_inspiratory_flow_l_s": "L/s",
    "respiratory_cycle_peak_expiratory_flow_l_s": "L/s",
    "respiratory_cycle_end_expiratory_flow_l_s": "L/s",
    "respiratory_cycle_peak_muscle_pressure_cmH2O": "cmH2O",
    "respiratory_cycle_peak_airway_pressure_cmH2O": "cmH2O",
    "respiratory_cycle_resistive_work_j_breath": "J/breath",
    "respiratory_cycle_muscle_work_j_breath": "J/breath",
    "respiratory_cycle_ventilator_work_j_breath": "J/breath",
    "respiratory_cycle_pv_hysteresis_j_breath": "J/breath",
    "respiratory_cycle_total_work_j_breath": "J/breath",
    "respiratory_cycle_expiratory_flow_limited_fraction": "dimensionless",
    "respiratory_cycle_time_constant_s": "s",
    "respiratory_ventilator_mean_trigger_delay_s": "s",
    "respiratory_ventilator_mean_cycling_delay_s": "s",
    "respiratory_ventilator_ineffective_trigger_fraction": "dimensionless",
    "respiratory_ventilator_double_trigger_fraction": "dimensionless",
    "respiratory_ventilator_premature_cycling_fraction": "dimensionless",
    "respiratory_ventilator_delayed_cycling_fraction": "dimensionless",
    "respiratory_ventilator_autotrigger_fraction": "dimensionless",
    "respiratory_ventilator_asynchrony_index_pct": "%",
    "respiratory_ventilator_patient_efforts_per_min": "1/min",
    "respiratory_ventilator_breaths_per_min": "1/min",
    "respiratory_ventilator_trigger_pressure_time_product_cmH2O_s": "cmH2O*s",
    "respiratory_ventilator_neural_inspiratory_time_s": "s",
    "arterial_o2_content_ml_dl": "mL O2/dL blood",
    "mixed_venous_o2_content_ml_dl": "mL O2/dL blood",
    "mixed_venous_o2_sat_pct": "%",
    "oxygen_delivery_ml_min": "mL O2/min",
    "oxygen_extraction_ratio": "dimensionless",
    "vo2_demand_ml_min": "mL O2/min",
    "vo2_ml_min": "mL O2/min",
    "oxygen_debt_ml_min": "mL O2/min unmet demand",
    "aerobic_fraction": "dimensionless",
    "sodium_mmol_l": "mmol/L",
    "potassium_mmol_l": "mmol/L",
    "chloride_mmol_l": "mmol/L",
    "strong_ion_difference_apparent_mEq_l": "mEq/L",
    "strong_ion_gap_mEq_l": "mEq/L",
    "albumin_g_dl": "g/dL",
    "phosphate_mmol_l": "mmol/L",
    "total_co2_mmol_l": "mmol/L",
    "arterial_total_co2_mmol_l_blood": "mmol CO2 equivalents/L whole blood",
    "mixed_venous_pco2_mmHg": "mmHg",
    "mixed_venous_total_co2_mmol_l_blood": "mmol CO2 equivalents/L whole blood",
    "rbc_ph": "dimensionless",
    "rbc_bicarbonate_mmol_l": "mmol/L RBC water",
    "carbamino_co2_mmol_l_blood": "mmol CO2 equivalents/L whole blood",
    "chloride_shift_plasma_mmol_l": "mmol/L plasma",
    "haldane_co2_content_gain_mmol_l": "mmol CO2 equivalents/L whole blood",
    "exchangeable_co2_pool_mmol": "mmol CO2 equivalents",
    "vco2_elimination_ml_min": "mL CO2/min (STPD equivalent)",
    "effective_co2_ventilation_l_min": "L/min effective for CO2 elimination",
    "anion_gap_mEq_l": "mEq/L",
    "gfr_ml_min": "mL/min",
    "urine_ammonium_mmol_min": "mmol/min",
    "adh_relative": "relative",
    "renin_relative": "relative",
    "angiotensin_ii_relative": "relative",
    "aldosterone_relative": "relative",
    "urine_flow_ml_min": "mL/min",
    "plasma_osmolality_mOsm_kg": "mOsm/kg",
    "ecf_volume_l": "L",
    "renal_function_fraction": "dimensionless",
    "probe_gut_mg": "mg",
    "probe_plasma_mg_l": "mg/L",
    "probe_effect_site_mg_l": "mg/L",
    "probe_total_body_mg": "mg",    "glucagon_pg_ml": "pg/mL",
    "sc_insulin_depot1_model_units": "OpenHumSim model-units",
    "sc_insulin_depot2_model_units": "OpenHumSim model-units",
    "sc_insulin_absorption_model_units_min": "OpenHumSim model-units/min",
    "glucagon_counterregulatory_egp_mg_kg_min": "mg/kg/min",
    "icf_volume_l": "L",
    "ecf_effective_tonicity_mOsm_l": "mOsm/L",
    "icf_effective_tonicity_mOsm_l": "mOsm/L",
    "osmotic_water_shift_l_min": "L/min",
    "potassium_transcellular_flux_mmol_min": "mmol/min",
    "potassium_transcellular_target_mmol_l": "mmol/L",

}

ACTION_SEMANTICS = {
    "insulin": {"native": "0..1", "meaning": "abstract exogenous insulin bolus per decision", "unit": "model units/decision"},
    "oral_carbs": {"native": "0..1", "meaning": "oral glucose-equivalent bolus", "unit": "g/decision"},
    "exercise": {"native": "0..1", "meaning": "exercise intensity held over decision interval", "unit": "dimensionless"},
    "saline": {"native": "0..1", "meaning": "0.9% NaCl bolus", "unit": "mL/decision"},
    "oxygen": {"native": "0..1", "meaning": "FiO2 control mapped from room air to maximum FiO2", "unit": "dimensionless"},
    "ventilation_pressure_assist": {"native": "0..1", "meaning": "positive airway-pressure assist amplitude passed through respiratory mechanics", "unit": "cmH2O"},
    "oral_water": {"native": "0..1", "meaning": "oral free-water bolus", "unit": "mL/decision"},
    "oral_probe_compound": {"native": "0..1", "meaning": "generic PBPK probe bolus", "unit": "mg/decision"},
}
